# .github/workflows/ci.yml
name: CI – Cloudinary React Native SDK

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - run: npm run prepack
      - run: npm test
